-- Generated by multilingual pipeline (zh-Hans): type_names
return {
  ["BUG"] = "虫",
  ["DRAGON"] = "龙",
  ["ELECTRIC"] = "电",
  ["FIGHTING"] = "格斗",
  ["FIRE"] = "火",
  ["FLYING"] = "飞行",
  ["GHOST"] = "幽灵",
  ["GRASS"] = "草",
  ["GROUND"] = "地面",
  ["ICE"] = "冰",
  ["NORMAL"] = "一般",
  ["POISON"] = "毒",
  ["PSYCHIC_TYPE"] = "超能力",
  ["ROCK"] = "岩石",
  ["WATER"] = "水",
}
