#!/usr/bin/env python3
"""Import reviewed Simplified Chinese Gen 2 descriptions.

The move/item wording comes from the official Simplified Chinese text in the
pinned PokéCorpus Ultra Sun/Ultra Moon dump.  Pokédex prose is already present
in this seed as a user-reviewed compact translation of both cartridge pages;
this tool only splits that prose between the two runtime pages.

This importer is intentionally not part of the normal seed build.  It records
the one-time, reproducible provenance step without making release builds depend
on two external source checkouts.
"""

from __future__ import annotations

import argparse
import re
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LANG = ROOT / "seeds" / "zh-Hans" / "gsc-gs" / "lang"


ITEM_ALIASES = {
    "BERRY": "橙橙果",
    "BITTER_BERRY": "柿仔果",
    "BURNT_BERRY": "利木果",
    "CALCIUM": "特攻增强剂",
    "ELIXER": "ＰＰ多项小补剂",
    "ETHER": "ＰＰ单项小补剂",
    "GOLD_BERRY": "文柚果",
    "HP_UP": "ＨＰ增强剂",
    "ICE_BERRY": "莓莓果",
    "MAX_ELIXER": "ＰＰ多项全补剂",
    "MAX_ETHER": "ＰＰ单项全补剂",
    "MINT_BERRY": "零余果",
    "MIRACLEBERRY": "木子果",
    "MYSTERYBERRY": "苹野果",
    "PP_UP": "ＰＰ提升剂",
    "PRZCUREBERRY": "樱子果",
    "PSNCUREBERRY": "桃桃果",
}


# Items removed after Gen 2 have no modern official description to import.
# These short translations follow pokegold's original description records.
ITEM_TEXT = {
    "BASEMENT_KEY": "可以打开地下仓库的门。",
    "BERSERK_GENE": "提高攻击，但会陷入混乱。",
    "BICYCLE": "可快速移动的折叠式自行车。",
    "BLUESKY_MAIL": "印有蓝天图案的信纸。",
    "BRICK_PIECE": "一块稀有的砖头碎片。",
    "CARD_KEY": "可以打开广播塔里的卷帘门。",
    "EON_MAIL": "印有伊布图案的信纸。",
    "FLOWER_MAIL": "印有花朵图案的信纸。",
    "GOLD_LEAF": "一片奇怪的金色叶子。",
    "GORGEOUS_BOX": "打开后看看里面有什么。",
    "ITEMFINDER": "可以查找附近看不见的道具。",
    "ITEM_46": "会发出清澈音色的神秘铃铛。",
    "ITEM_73": "用途不明的神秘精灵球。",
    "ITEM_74": "用来记录布埃纳积分的卡片。",
    "ITEM_81": "可以用来兑换宝可梦蛋的券。",
    "LITEBLUEMAIL": "印有迷你龙图案的信纸。",
    "LOVELY_MAIL": "印有爱心图案的信纸。",
    "LOST_ITEM": "模仿少女遗失的宝可梦玩偶。",
    "MACHINE_PART": "发电厂机器上遗失的零件。",
    "MIRAGE_MAIL": "印有梦幻图案的信纸。",
    "MORPH_MAIL": "印有百变怪图案的信纸。",
    "MUSIC_MAIL": "印有天然雀图案的信纸。",
    "MYSTERY_EGG": "从宝可梦爷爷那里得到的蛋。",
    "NORMAL_BOX": "打开后看看里面有什么。",
    "PASS": "乘坐磁悬浮列车时所需的车票。",
    "PINK_BOW": "携带后，一般属性招式的威力会提高。",
    "POKE_FLUTE": "能吹出让宝可梦醒来的美妙音色。",
    "POLKADOT_BOW": "携带后，一般属性招式的威力会提高。",
    "PORTRAITMAIL": "印有携带者肖像的信纸。",
    "RAINBOW_WING": "闪耀着虹色光辉的神秘羽毛。",
    "RED_SCALE": "从红色暴鲤龙身上掉落的鳞片。",
    "SECRETPOTION": "能让任何宝可梦完全恢复精神的药。",
    "SILVER_LEAF": "一片奇怪的银色叶子。",
    "SILVER_WING": "闪耀着银色光辉的神秘羽毛。",
    "SQUIRTBOTTLE": "给植物浇水时使用的喷壶。",
    "S_S_TICKET": "乘坐水流号时所需的船票。",
    "SURF_MAIL": "印有拉普拉斯图案的信纸。",
    "TOWN_MAP": "可以随时查看城都地区的地图。",
}


def read_lua_map(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    pattern = re.compile(r'^  \["((?:\\.|[^"])*)"\] = "((?:\\.|[^"])*)",$')
    for line in path.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match:
            key = match.group(1).replace(r'\"', '"').replace(r"\\", "\\")
            value = match.group(2).replace(r"\n", "\n").replace(r'\"', '"').replace(r"\\", "\\")
            values[key] = value
    return values


def lua_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", r"\n")


def write_lua_map(path: Path, title: str, values: dict[str, str]) -> None:
    lines = [f"-- Generated by {Path(__file__).name}: {title}", "return {"]
    lines.extend(f'  ["{lua_quote(key)}"] = "{lua_quote(values[key])}",' for key in sorted(values))
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def corpus_rows(corpus: Path) -> tuple[list[str], list[str], list[str]]:
    base = corpus / "corpus" / "UltraSunUltraMoon"
    qids = (base / "qid_common.txt").read_text(encoding="utf-8-sig").splitlines()
    english = (base / "en_common.txt").read_text(encoding="utf-8-sig").splitlines()
    chinese = (base / "zh-Hans_common.txt").read_text(encoding="utf-8-sig").splitlines()
    if not (len(qids) == len(english) == len(chinese)):
        raise ValueError("PokéCorpus qid/en/zh-Hans files are not aligned")
    return qids, english, chinese


def section(qids: list[str], values: list[str], number: int) -> dict[int, str]:
    result: dict[int, str] = {}
    pattern = re.compile(rf"usum\.common\.{number}\.(\d+)")
    for qid, value in zip(qids, values):
        match = pattern.fullmatch(qid)
        if match:
            result[int(match.group(1))] = value.replace(r"\n", "\n")
    return result


def normalise(value: str) -> str:
    return "".join(ch for ch in unicodedata.normalize("NFKC", value) if ch.isalnum()).casefold()


def compact_lines(value: str, width: int = 18) -> str:
    text = value.replace("\n", "")
    if len(text) > width * 3:
        raise ValueError(f"description exceeds three 18-cell rows: {value!r}")
    return text


def move_ids(pokegold: Path) -> list[str]:
    result = []
    for line in (pokegold / "constants" / "move_constants.asm").read_text(encoding="utf-8").splitlines():
        match = re.match(r"\s*const\s+([A-Z0-9_]+)", line)
        if match and match.group(1) != "NO_MOVE":
            result.append(match.group(1))
    return result[:251]


def split_dex(value: str) -> tuple[str, str]:
    text = value.replace("\n", "")
    middle = len(text) // 2
    candidates = [index + 1 for index, char in enumerate(text) if char in "。！？；"]
    candidates = [index for index in candidates if len(text) * 0.25 <= index <= len(text) * 0.75]
    if not candidates:
        candidates = [index + 1 for index, char in enumerate(text) if char in "，、"]
        candidates = [index for index in candidates if len(text) * 0.35 <= index <= len(text) * 0.65]
    cut = min(candidates, key=lambda index: abs(index - middle)) if candidates else middle
    return compact_lines(text[:cut]), compact_lines(text[cut:])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pokegold", type=Path, required=True)
    parser.add_argument("--poke-corpus", type=Path, required=True)
    args = parser.parse_args()

    qids, _english, chinese = corpus_rows(args.poke_corpus)

    usum_moves = section(qids, chinese, 117)
    ids = move_ids(args.pokegold)
    if len(ids) != 251 or not all(index in usum_moves for index in range(1, 252)):
        raise ValueError("expected all 251 Gen 2 moves and official descriptions")
    move_values = {move_id: compact_lines(usum_moves[index]) for index, move_id in enumerate(ids, 1)}
    write_lua_map(LANG / "move_descriptions.lua", "move_descriptions", move_values)

    item_names = read_lua_map(LANG / "item_names.lua")
    usum_item_names = section(qids, chinese, 40)
    usum_item_text = section(qids, chinese, 39)
    modern = {
        normalise(name): usum_item_text[index]
        for index, name in usum_item_names.items()
        if index in usum_item_text and name
    }
    item_values: dict[str, str] = {}
    for item_id, translated_name in item_names.items():
        lookup_name = ITEM_ALIASES.get(item_id, translated_name)
        value = ITEM_TEXT.get(item_id) or modern.get(normalise(lookup_name))
        if value is None and item_id.startswith(("TM_", "HM_")):
            value = "可让宝可梦学会一个招式。"
        if value is None and item_id.startswith("ITEM_"):
            value = "未使用的道具。"
        if value is None:
            raise ValueError(f"no reviewed description for {item_id} ({translated_name})")
        item_values[item_id] = compact_lines(value)
    write_lua_map(LANG / "item_descriptions.lua", "item_descriptions", item_values)

    dex = read_lua_map(LANG / "species_dex_text.lua")
    dex2_path = LANG / "species_dex_text2.lua"
    existing_second = read_lua_map(dex2_path) if dex2_path.exists() else {}
    first: dict[str, str] = {}
    second: dict[str, str] = {}
    for species_id, value in dex.items():
        full_value = value + existing_second.get(species_id, "")
        first[species_id], second[species_id] = split_dex(full_value)
    write_lua_map(LANG / "species_dex_text.lua", "species_dex_text page 1", first)
    write_lua_map(LANG / "species_dex_text2.lua", "species_dex_text page 2", second)

    print(f"wrote {len(move_values)} moves, {len(item_values)} items and {len(dex)} two-page dex entries")


if __name__ == "__main__":
    main()
